<!-- css -->
<?php $this->headLink()
            ->prependStylesheet($this->basePath() . '/js/jqueryUI/themes/ui-darkness/jquery-ui.css'); ?>
<!-- Js -->            
<?php  $this->headScript()
            ->appendFile($this->basePath() . '/js/jqueryUI/ui/jquery-ui.custom.js') 
            ->appendFile($this->basePath() . '/js/file_manager_delete_file_ajax.js')
			->appendFile($this->basePath() . '/js/file_manager_add_file.js'); ?>
<h1>Pregled Podataka</h1>
<table class="table">
<?php foreach ($rowset as $row) {?>
    <tr><td>Predmet</td>			<td><?php  echo $row->doc_title;?></td></tr>
    <tr><td>Datum unosa:</td>		<td><?php  echo $row['date_of_entry']; ?></td></tr>
    <tr><td>Delovodni broj:</td>	<td><?php  echo $row['doc_id']; ?></td></tr>
    <tr><td>Firma ili lice</td>		<td><?php  echo $row->company;?></td></tr>
    <tr><td>Njihov broj</td>		<td><?php  echo $row['doc_company_id']; ?></td></tr>
    <tr><td>Datum na dokumentu</td>	<td><?php  echo $row['date']; ?></td></tr>
    <tr><td>Lokacija dokumenta</td>	<td><?php  echo $row->doc_location;?></td></tr>
    <tr><td>Napomena</td>			<td><?php  echo $row['remark']; ?></td></tr> 
	<?php
	}
	?>

	<?php if($there_are_files)
	{
	?>
	
		<table class="table">
		<tr><td colspan="4"><h1>Pregled Fajlova</h1></td>
        <tr>
            <th>Komentar</th>
            <th>Ime fajla</th>
            <th>Akcija</th>    
            <th>Akcija</th>
        </tr>
	<?php 
		foreach ($files as $file) : ?>
		<tr>
			<td><?php echo $this->escapeHtml($file->label);?></td>
			<td><?php echo $this->escapeHtml($file->original_file_name);?></td>
			<td><a href="<?php echo $this->url('file-manager/default', 
					array('controller' => 'FileManager', 'action'=>'view', 'id' => $file->id));?>">Pogledaj</a>    </td>
		<td><a href="/file-manager/FileManager/download/<?php echo $file->id;?>"</a>Preuzmi fajl</td>
		</tr>
		<?php 
		endforeach; 
	}
?>   
</table>